# Generated by Django 4.2.3 on 2023-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatars/'),
            preserve_default=False,
        ),
    ]
