# Generated by Django 4.2.3 on 2023-07-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chat_messages_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='permission_user1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='permission_user2',
            field=models.BooleanField(default=False),
        ),
    ]
