# Generated by Django 4.2.3 on 2023-08-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('random_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randompost',
            old_name='author',
            new_name='author_id',
        ),
    ]
